Repository zero-to-mastery/Keiko-Corp, pull requests merged in 2020-10, with the labels that each got.

#207 Finished the footer as in the design
  assets/css/footer.css
  assets/css/styles.css
  index.html
Labels: Missing Issue ID

#337 added name to Contributors list
  CONTRIBUTORS.md
Labels: invalid

#201 Footer branch
  assets/css/nav-styles.css
  index.html
Labels: Conflict Present

#331 Styling the Our Client Love Us section
  assets/css/styles.css
Labels: Conflict Present

#155 Adding a Cool animation
  assets/css/styles.css
Labels: Missing Issue ID

#162 add some style and changing the team names
  assets/css/nav-styles.css
  assets/css/styles.css
  index.html
  pull_request_template.md
Labels: Missing Issue ID

#241 add name in contributors list
  CONTRIBUTORS.md
Labels: invalid

#279 Update CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: invalid

#413 contribution-edit
  CONTRIBUTORS.md
Labels: question

#500 adjustments on script.js - removed merge/conflict strings
  assets/js/script.js
Labels: question

#493 Made the company section responsive #478
  assets/css/companies-banner.css
  index.html
Labels: question

#535 Added my name in CONTRIBUTORS.md file
  CONTRIBUTORS.md
Labels: invalid

#641 Updated CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: invalid

#660 updated CONTRIBUTERS.md
  CONTRIBUTORS.md
Labels: invalid

#815 my info to the contibutors.md file #814
  CONTRIBUTORS.md
Labels: invalid, question

#845 Improving site
  assets/css/contact.css
  assets/css/login.css
  assets/css/meet-the-team.css
  assets/css/nav-styles.css
  assets/css/styles.css
  contact.html
  index.html
  login.html
Labels: change requested

#897 Fix home button in dark mode
  index.html
Labels: change requested

#920 Added name in contributor list after first PR is merged
  CONTRIBUTORS.md
Labels: invalid

#929 fixes #927
  index.html
Labels: invalid

#965 Fixed design for the About Us Page
  about.html
Labels: change requested

#970 Blog navbar fix along with input styling
  assets/css/blog_page.css
  assets/css/footer.css
  blog.html
Labels: change requested

#992 contributors-edit (added <dhakshinesh>)
  CONTRIBUTORS.md
Labels: invalid

#1006 Commenting login.html
  login.html
Labels: invalid

#1007 Commenting and Grammar in meet-the-team.html
  meet-the-team.html
Labels: invalid
